import type { Metadata } from "next";
import { Geist, Geist_Mono, Kanit, Prompt } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const kanitSans = Kanit({
  variable: "--font-kanit",
  subsets: ["latin", "thai"],
  weight: ["200","300","400","500","600","700","800","900"],
});

const promptSans = Prompt({
  variable: "--font-prompt",
  subsets: ["latin", "thai"],
  weight: ["200","300","400","500","600","700","800","900"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Docs App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel='stylesheet' href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' />
      </head>
      <body className={`${kanitSans.variable} ${promptSans.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
